SELECT * FROM Employees e

BEGIN trans 
CREATE TABLE SAMPLE_PAYROLL(
	EMPLOYEEID   INT              NOT NULL,
   ENAME VARCHAR (20)     NOT NULL,
   HOURLYWAGE MONEY NOT NULL,
   WORKINGHOUR INT NOT NULL,
   --GROSSPAY MONEY NOT NULL,
   --FEDERALALLOW INT NOT NULL,
   --StateTax MONEY NOT NULL,
   --FederalIncomeTax MONEY NOT NULL,
   --SocialSecurity MONEY NOT NULL,
   --Medicare MONEY NOT NULL,
   --TotalTaxWithheld MONEY NOT NULL,
   --InsuranceDeduction MONEY NOT NULL,
   NetPay MONEY NOT NULL
);
SELECT * FROM targeted
INSERT INTO SAMPLE_PAYROLL
(
	EMPLOYEEID,
	ENAME,
	HOURLYWAGE,
	WORKINGHOUR,
	NetPay
)
SELECT * FROM targeted
COMMIT trans